Running SLURM prolog script on pink51.cluster.local
===============================================================================
Job started on Mon May  5 21:03:29 BST 2025
Job ID          : 7369692
Job name        : AdaNF_MNLI
WorkDir         : /mainfs/lyceum/be1g21/LoftQ_Private/custom_loftq
Command         : /mainfs/lyceum/be1g21/LoftQ_Private/custom_loftq/AdaNF_mnli.sh
Partition       : lyceum
Num hosts       : 1
Num cores       : 16
Num of tasks    : 1
Hosts allocated : pink51
Job Output Follows ...
===============================================================================
Starting AdaNF MNLI run...
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_machines` was set to a value of `1`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
[2025-05-05 21:05:13,769] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/mainfs/lyceum/be1g21/LoftQ_Private/custom_loftq/run_loftq.py", line 12, in <module>
    base_args, model_args, data_args, training_args = parser.parse_args_into_dataclasses()
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lyceum/be1g21/.conda/envs/loftq/lib/python3.12/site-packages/transformers/hf_argparser.py", line 358, in parse_args_into_dataclasses
    obj = dtype(**inputs)
          ^^^^^^^^^^^^^^^
  File "<string>", line 137, in __init__
  File "/lyceum/be1g21/.conda/envs/loftq/lib/python3.12/site-packages/transformers/training_args.py", line 1648, in __post_init__
    raise ValueError(
ValueError: --load_best_model_at_end requires the save and eval strategy to match, but found
- Evaluation strategy: IntervalStrategy.NO
- Save strategy: SaveStrategy.EPOCH
Traceback (most recent call last):
  File "/lyceum/be1g21/.conda/envs/loftq/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/lyceum/be1g21/.conda/envs/loftq/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 50, in main
    args.func(args)
  File "/lyceum/be1g21/.conda/envs/loftq/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1213, in launch_command
    simple_launcher(args)
  File "/lyceum/be1g21/.conda/envs/loftq/lib/python3.12/site-packages/accelerate/commands/launch.py", line 795, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/lyceum/be1g21/.conda/envs/loftq/bin/python', 'run_loftq.py', '--model_name_or_path', 'microsoft/deberta-v3-base', '--data_name', 'glue', '--task_name', 'mnli', '--loftq', '--quant_method', 'adanf', '--int_bit', '2', '--adanf_pnorm', '3', '--adanf_grid_size', '10', '--reduced_rank', '32', '--num_iter', '2', '--gradient_accumulation_steps', '1', '--per_device_train_batch_size', '32', '--learning_rate', '1e-4', '--num_train_epochs', '5', '--output_dir', '/scratch/be1g21/trained_models/adanf_mnli_b2_r32_lr1e-4_e5', '--logging_dir', '/scratch/be1g21/trainer_outputs/adanf_mnli_logs', '--logging_steps', '50', '--evaluation_strategy', 'epoch', '--save_strategy', 'epoch', '--save_total_limit', '2', '--load_best_model_at_end', 'True', '--metric_for_best_model', 'accuracy', '--true_quantization']' returned non-zero exit status 1.
==============================================================================
Running epilogue script on pink51.

Submit time  : 2025-05-05T21:03:21
Start time   : 2025-05-05T21:03:29
End time     : 2025-05-05T21:05:33
Elapsed time : 00:02:04 (Timelimit=1-00:00:00)

Job ID: 7369692
Cluster: i5
User/Group: be1g21/fp
State: FAILED (exit code 1)
Nodes: 1
Cores per node: 16
CPU Utilized: 00:00:18
CPU Efficiency: 0.91% of 00:33:04 core-walltime
Job Wall-clock time: 00:02:04
Memory Utilized: 1.09 GB
Memory Efficiency: 0.00% of 16.00 B

